# Generated by Django 5.2.4 on 2025-08-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('customer', 'Customer'), ('administrative', 'Administrative')], default='customer', max_length=50),
        ),
    ]
