# Generated by Django 5.2.4 on 2025-08-16 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('session_type', models.CharField(blank=True, choices=[('virtual', 'VIRTUAL'), ('in-person', 'IN-PERSON')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('meeting_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.customer')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='account.trainer')),
            ],
        ),
    ]
