# Generated by Django 5.2.4 on 2025-08-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_started',
            field=models.BooleanField(default=False),
        ),
    ]
